env:
  isTestnet: false
  discord:
    discordToken: OTA0NDcwNDUzMjc4NjE3NjAw.GAJrjt.puUo3ND91vnKdBIUFrNYdTUnpUjeD4hictHMnk
  pg:
    host: postgres-zilkroad-mainnet
    database: postgres
    port: 5432
    user: user_function_readonly
    password: NNq7!aXfZRig3U!
  currentNetwork: https://api.zilliqa.com
  enableCache: true
  cacheAge: 300
  redisUrl: redis-headless.redis.svc.cluster.local
  redisPort: 6379
  # REPLACE
  marketplaceContract: 0xad43392d1750771e58931801ddc274e5984660b4
  tokens:
    # REPLACE ALL TOKENS
    wzil: 864895d52504c388a345ef6cd9c800dbbd0ef92a
    gzil: 607d0ba69c3680ed07262e5d80be98c401fd612c
    xsgd: 56906c825a6df74032ea40b4ff882b5970f3d0a8
    zwbtc: 9fe903bf7c48d6bf4bcc7c53e77d3d2a2ebbf5ae
    zeth: 049346a00627b89441b2d5110b09c376913f19ff
    zusdt: 9fce53c80e07fddb02450fc9b435b0a7781b68a8
    duck: e743ff40e780fe08dee4e2ad830983d1979ff2e6

namespace: zilkroad-mainnet

ingress:
  enabled: True
  host: public-api.zilkroad.io

image:
  app:
    pullSecret: aws-registry

replicas: 1
