env:
  isTestnet: true
  discordToken: OTA0NDcwNDUzMjc4NjE3NjAw.GgDcRZ.XlpogCVhHB5TNh5wUmdryQ27ABIyWiZ4_20EyA
  pg:
    host: postgres-zilkroad.postgres.svc.cluster.local
    database: postgres
    port: 5432
    user: user_function_readonly
    password: a}TKXA>M45dD#Ws#TAs+4a=MM8S
  currentNetwork: https://dev-api.zilliqa.com
  disableCache: false
  tokens:
    wzil: 864895d52504c388a345ef6cd9c800dbbd0ef92a
    gzil: 607d0ba69c3680ed07262e5d80be98c401fd612c
    xsgd: 56906c825a6df74032ea40b4ff882b5970f3d0a8
    zwbtc: 9fe903bf7c48d6bf4bcc7c53e77d3d2a2ebbf5ae
    zeth: 2e8e7d992c8dc04f89c4e5e798b2fa8345885b18
    zusdt: 9fe903bf7c48d6bf4bcc7c53e77d3d2a2ebbf5ae
    duck: 30832ed39781b7840485f79fb971bb67a595a2b2

namespace: zilkroad-testnet

ingress:
  enabled: True
  host: staging-public-api.zilkroad.io

image:
  app:
    pullSecret: aws-registry

replicas: 3
