image:
  app:
    url: 465700395685.dkr.ecr.eu-west-1.amazonaws.com/zilkroad-private/public-api
    tag: latest
    pullPolicy: IfNotPresent
    pullSecret: ~

port: 5000
targetPort: 5000
namespace: devnet

logPath: /app/logs

replicas:
  publicApi: 1

env:
  isTestnet: true
  discordToken: OTA0NDcwNDUzMjc4NjE3NjAw.GgDcRZ.XlpogCVhHB5TNh5wUmdryQ27ABIyWiZ4_20EyA
  pg:
    host: postgres
    database: postgres
    port: 5432
    user: postgres
    password: postgres_password

resources:
  limits:
    cpu: 0.2
    memory: 128M 
  requests:
    cpu: 0.2
    memory: 128M 
