name: Lint and Build public API image

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'public-api/**'

  # Allows manual trigger
  workflow_dispatch:

env:
  CONTAINER_NAME: public-api 
  IMAGE_TAG: ${{ github.sha }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: hadolint/hadolint-action@v1.5.0
      with:
        dockerfile: public-api/Dockerfile
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build Docker image
      working-directory: ./public-api
      id: build-image
      run: |
        docker build -t $CONTAINER_NAME:$IMAGE_TAG .
